/* 
 * BlockMarkets Cryptocurrency API
 *
 * The BlockMarkets API provides real-time and historical market data on cryptocurrencies from the world's leading crypto exchanges. Sign up for a free, unlimited API key at [BlockMarkets Cryptocurrency API](https://www.blockmarkets.io/cryptocurrency-api).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlockMarkets.Rest.Api;
using BlockMarkets.Rest.Model;
using BlockMarkets.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlockMarkets.Rest.Test
{
    /// <summary>
    ///  Class for testing Empty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmptyTests
    {
        // TODO uncomment below to declare an instance variable for Empty
        //private Empty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Empty
            //instance = new Empty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Empty
        /// </summary>
        [Test]
        public void EmptyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Empty
            //Assert.IsInstanceOfType<Empty> (instance, "variable 'instance' is a Empty");
        }



    }

}
